### ISSUE TITLE
MaskField does not work for integer choices

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [TCM-dev/EasyAdminFieldsBundle#2]
Hello,

I've just tried using your library for masking fields based on a ChoiceField whose options are integers (I'm using an integer enum behind this ChoiceField), and it does not work.

Here is a PR that fixes this: https://github.com/TCM-dev/EasyAdminFieldsBundle/pull/1

Regards,
Yonn Trimoreau

**Comment by TCM-dev** [comment]
Thank you for the PR, I merged it, just so you know, I barely maintain this librairy, the maskfield is useful in many projects in my company but we still mostly use the "native" easy admin fields.
