### ISSUE TITLE
How to use MaskField with an AssociationField?

### ISSUE THREAD

**Issue by BurningDog** [TCM-dev/EasyAdminFieldsBundle#4]
I have 2 fields - `title` (an `AssociationField`) and `titleOther` (a `TextField`). I'd like to use `MaskField` to hide `titleOther` by default, and show it when selecting "Other" from the `title` dropdown select.

The entity id of "Other" is 9. None of the following works (i.e. the `titleOther` text field doesn't show when selecting "Other"):

```php
MaskField::adapt(
            AssociationField::new('title'),
            [
                'Other' => [
                    'titleOther',
                ],
                'None of the above' => [
                    'titleOther',
                ],
                '9' => [
                    'titleOther',
                ],
                9 => [
                    'titleOther',
                ],
            ]
        );
``` 

Any suggestions? It works fine on a `ChoiceField`.

**Comment by TCM-dev** [comment]
Either it does not manage to retrieve the correct value of the association field whend it updates or it somehow does not manage to "find" the field in the dom (it's hard to support every kind of field)
Anyway, I'll probably have to fix another bug in the package soon for my company (it looks like maskfield does not work with a multi choice field), I will try to take a look at that too if I can.

As for the mapping, I think I will go with the id and not the text value

**Comment by BurningDog** [comment]
Thanks! It also might be that the `value` is an array of values, so it could be something like:

```php
MaskField::adapt(
            AssociationField::new('title'),
            [
                []['Other'] => [
                    'titleOther',
                ],
```

...but just guessing here!

**Comment by TCM-dev** [comment]
After testing locally, it works for me with a mapping configuration using ids (either int or string)
```php
[
  '1' => ['field'],
  1 => ['field']
]
```

We will try to add an option to chose between the field value and the field displayed value later

If it does not work for you, maybe you forgot to configure the bundle assets in the DashboardController configureAssets method (as shown in the README), or you're not on the latest version?
